### ISSUE TITLE
Need help - can't get it running. Didn't find a discussion forum.

### ISSUE THREAD

**Issue by jaguarman** [diogogpinto/filament-auth-ui-enhancer#10]
### What happened?

First, let me thank you for the idea and programming. The pics look great and I'd like to use the plugin.

I don't think it's a bug, but I didn't find a discussion forum, so I'm posting my problem here.
I installed the plugin, did all the steps, but I can't see any difference in behaviour. 
I'm a newbie to laravel/filament, so I don't really know how to debug.
What do you  or I need to debug the problem? 

### How to reproduce the bug

Please tell me, what you or I need to debug the problem.
Thank you all in advance.
Best regards
Peter

### Package Version

latest

### PHP Version

latest

### Laravel Version

latest

### Which operating systems does with happen with?

Windows

**Comment by diogogpinto** [comment]
Hey @jaguarman 

Please make sure that:

- You created and are using a custom theme (method viteTheme in your panel provider)
- You added plugin views to tailwind.config.json
- You are not using custom Login logic (or if you are, check if you set it up like this: https://github.com/diogogpinto/filament-auth-ui-enhancer?tab=readme-ov-file#auth-page-discovery)
- You ran `npm run build`

If you are new to filament, please go to filament docs and check if you did everything right when it comes to custom theming.

**Comment by jaguarman** [comment]
hello @diogogpinto, thanks for your kind response.

Not sure, what i shall do with the second pint you mentioned:
"The above content should be placed in your filament theme's tailwind.config.js file, under the /resources/css/filament path"

There is no css path inside the tailwind config. That's how it looks:

import preset from '../../../../vendor/filament/filament/tailwind.config.preset'

export default {
    presets: [preset],
    content: [
        './vendor/archilex/filament-filter-sets/**/*.php',
        './app/Filament/**/*.php',
        './resources/views/filament/**/*.blade.php',
        './vendor/filament/**/*.blade.php',
        './vendor/guava/filament-knowledge-base/src/**/*.php',
        './vendor/guava/filament-knowledge-base/resources/**/*.blade.php',
    ],
}


there is a theme.css file on the same folder level like this:

@import '/vendor/filament/filament/resources/css/theme.css';
@config 'tailwind.config.js';
@import '../../../../vendor/archilex/filament-filter-sets/resources/css/plugin.css';

where can I add this line?
 './vendor/diogogpinto/filament-auth-ui-enhancer/resources/**/*.blade.php',

Thank you.
Peter

**Comment by diogogpinto** [comment]
@jaguarman you can add the line:

```
'./vendor/diogogpinto/filament-auth-ui-enhancer/resources/**/*.blade.php',
```

in your tailwindconfig.js, in the content array:

```
content: [
'./vendor/archilex/filament-filter-sets//*.php',
'./app/Filament//.php',
'./resources/views/filament/**/.blade.php',
'./vendor/filament//*.blade.php',
'./vendor/guava/filament-knowledge-base/src//.php',
'./vendor/guava/filament-knowledge-base/resources/**/.blade.php',
'./vendor/diogogpinto/filament-auth-ui-enhancer/resources/**/*.blade.php',
],
}
````

Much like you did with your other plugins filament-knowledge-base.

**Comment by jaguarman** [comment]
Hello Diego,

thank you for your kind response.
Unfortunately it still does not work.
My standard panel is "app"

  return $panel
            ->default()
            ->id('app')
            ->path('app')

Is it possible that this causes the problem?
I have a custom the and a standard login:

     ->login()

I have this developer logins but I commented it out and still your auth
enhancer doesn't show up

              /*
                FilamentDeveloperLoginsPlugin::make()
                ->enabled(app()->environment('local'))
//                ->enabled(false)
                ->users([
                    'Super Admin' => ***@***.***',
                    'Admin FSP' => ***@***.***',
                    'Admin Vogtmann' => ***@***.***',
                    'SB FSP' => ***@***.***',
                    'SB Vogtmann' => ***@***.***',
                    'Melder FSP' => ***@***.***',
                    'Melder VOH' => ***@***.***',
                    'GF FSP' => ***@***.***',
                    'GF VOH' => ***@***.***',

                ])

                */

Do you have any idea what might go wrong, is there any code that I can
inspect or some debug information I can look at?

best regards
Peter


Am Di., 24. Dez. 2024 um 00:50 Uhr schrieb Diogo Pinto <
***@***.***>:
