### ISSUE TITLE
[Bug]: What's wrong why it looks like this?

### ISSUE THREAD

**Issue by devhoussam1998** [diogogpinto/filament-auth-ui-enhancer#6]
### What happened?

thei mage not displayed as expected I follow the README

### How to reproduce the bug

<img width="1819" alt="Screenshot 2024-10-22 at 17 59 43" src="https://github.com/user-attachments/assets/f3978fcc-8029-41d5-a8a8-3383dd88edbd">

### Package Version

v1.0.1

### PHP Version

^8.2

### Laravel Version

^11.9

### Which operating systems does with happen with?

macOS

**Comment by diogogpinto** [comment]
Hey @devhoussam1998 and @Jam0r85

It looks like you haven't registered the views in your custom theme and ran `npm run build` in your terminal.

If you created a custom theme like 'admin', navigate to `/resources/css/filament/admin` and add the following to your content array in tailwind.config.js:

```javascript
content: [
    './vendor/diogogpinto/filament-auth-ui-enhancer/resources/**/*.blade.php',
]
```

After, you should run `npm run build` in your terminal.

**Comment by Jam0r85** [comment]
I've 110% loaded this into my tailwind.config.js and still having the issue.

**Comment by diogogpinto** [comment]
> I've 110% loaded this into my tailwind.config.js and still having the issue.

Do you have any repo I can replicate to test this out? In all the tests we've run we never found this issue.

**Comment by Jam0r85** [comment]
![Screenshot 2024-10-22 at 18 27 16](https://github.com/user-attachments/assets/e58def13-0a1f-4872-a803-f5ac7976f056)
![Screenshot 2024-10-22 at 18 27 26](https://github.com/user-attachments/assets/93bcc2b9-7787-47fe-bbdd-14d031c40082)
![Screenshot 2024-10-22 at 18 27 45](https://github.com/user-attachments/assets/d66efe98-04c9-45a4-95e9-a0dbc2dabb43)

I don't at the moment i'm afraid. Mobile works fine? I'll see if I can sort one.

**Comment by diogogpinto** [comment]
> I don't at the moment i'm afraid. Mobile works fine? I'll see if I can sort one.

Weird. Would you mind sharing your plugin config methods? Or paste this one to test out:

```php
        AuthUIEnhancerPlugin::make()
            ->showEmptyPanelOnMobile(false)
            ->formPanelPosition('right')
            ->formPanelWidth('40%')
            ->emptyPanelBackgroundImageOpacity('70%')
            ->emptyPanelBackgroundImageUrl('https://images.pexels.com/photos/466685/pexels-photo-466685.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2')
```

**Comment by devhoussam1998** [comment]
> Hey @devhoussam1998 and @Jam0r85
> 
> It looks like you haven't registered the views in your custom theme and ran `npm run build` in your terminal.
> 
> If you created a custom theme like 'admin', navigate to `/resources/css/filament/admin` and add the following to your content array in tailwind.config.js:
> 
> ```js
> content: [
>     './vendor/diogogpinto/filament-auth-ui-enhancer/resources/**/*.blade.php',
> ]
> ```
> 
> After, you should run `npm run build` in your terminal.
> 
> You should note that this plugin requires a custom theme to run.

I already do that

**Comment by devhoussam1998** [comment]
I just add `'./vendor/diogogpinto/filament-auth-ui-enhancer/resources/**/*.blade.php',` in `/resources/css/filament/admin/tailwind.config.js`

**Comment by diogogpinto** [comment]
> ```
> AuthUIEnhancerPlugin::make()
>                     ->formPanelBackgroundColor(Color::Zinc, 300)
>                     ->formPanelPosition('right')
>                     ->mobileFormPanelPosition('bottom')
>                     ->formPanelWidth('40%')
>                     ->emptyPanelBackgroundImageUrl('https://images.unsplash.com/photo-1496449903678-68ddcb189a24?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'),
> ```

Whenever possible, please share a repo and open a new issue so we can debug this further. This seems more like a tailwind config thing, as many people were able to run the plugin.

Please reach out when ready! Thank you so much for your feedback, is greatly appreciated.

**Comment by tominal** [comment]
This definitely does not work out of the box and I can confirm it looks identical to the original poster here. I had to add custom CSS to get it to not do that:

```
.custom-auth-form-panel {
    width: var(--form-panel-width) !important;
}
```

**Comment by diogogpinto** [comment]
> This definitely does not work out of the box and I can confirm it looks identical to the original poster here. I had to add custom CSS to get it to not do that:
> 
> ```
> .custom-auth-form-panel {
>     width: var(--form-panel-width) !important;
> }
> ```

@tominal It worked for previous users and has worked out of the box for more than 6 panels I’m running in production until a couple of releases ago (haven’t upgraded the production websites just yet).

This night or tomorrow I will make a video installing the plugin from scratch in a fresh installation just to see if it works or not.

To say that it “definitely” does not work out of the box when thousand of other people have used it with no issues is quite a stretch and a bit, just a tiny bit maybe, misleading.

**Comment by tominal** [comment]
> > This definitely does not work out of the box and I can confirm it looks identical to the original poster here. I had to add custom CSS to get it to not do that:
> > 
> > ```
> > .custom-auth-form-panel {
> >     width: var(--form-panel-width) !important;
> > }
> > ```
> 
> @tominal It worked for previous users and has worked out of the box for more than 6 panels I’m running in production until a couple of releases ago (haven’t upgraded the production websites just yet).
> 
> This night or tomorrow I will make a video installing the plugin from scratch in a fresh installation just to see if it works or not.
> 
> To say that it “definitely” does not work out of the box when thousand of other people have used it with no issues is quite a stretch and a bit, just a tiny bit maybe, misleading.

Looking forward to the video!

**Comment by diogogpinto** [comment]
@tominal I was almost heading to bed when I got your email. Here you go, a video 3min and 35 sec video setting up Laravel and Filament from scratch with the plugin working out of the box, as promised.

https://github.com/user-attachments/assets/cb776f59-59fc-4a6a-bf3b-3e97d08107fd

**Comment by tominal** [comment]
Maybe a CSS attribute not supported on Arc, yet? Does your Chrome browser show the same thing?

**Comment by diogogpinto** [comment]
> Maybe a CSS attribute not supported on Arc, yet? Does your Chrome browser show the same thing?

Arc is chrome based, so the output should be similar. In the mobile browsers (Arc search, chrome and safari everything’s working as expected on prod apps)

In bed now but will update you tomorrow.

**Comment by diogogpinto** [comment]
> Maybe a CSS attribute not supported on Arc, yet? Does your Chrome browser show the same thing?

Here's a Safari, Chrome and Arc screenshot

<img width="1840" alt="Image" src="https://github.com/user-attachments/assets/03f7f16d-5c00-4737-b7c9-c0d7c9118951" />

<img width="2056" alt="Image" src="https://github.com/user-attachments/assets/3d763277-7234-479e-8b1e-867f644f73e1" />
